POST http://localhost:5000/v1/api/vaults/register/
Content-Type: application/json

{
  "firstName": "b",
  "lastName": "b",
  "email": "b@b.com",
  "masterPassword": "hello_world!"
}

###

GET http://localhost:5000/v1/api/vaults/verify/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2YXVsdCI6eyJmaXJzdE5hbWUiOiJiIiwibGFzdE5hbWUiOiJiIiwiZW1haWwiOiJiQGIuY29tIiwiaGFzaGVkTWFzdGVyUGFzc3dvcmQiOiIkMmIkMTUkbzJsTDJaLmN0SUt6bkpHQXEzelc1dS5tUjByUmxNYjNVcEcyOEVTVG0xSmdMNFZjek1NekMiLCJfaWQiOiI2NGI3NzRlMGJkM2E5MjA4MTMxOTM2ZWEiLCJfX3YiOjB9LCJpYXQiOjE2ODk3NDQ2MDh9.xz_weuONhzaDwTYIWUg4tezKaXLeTVVVsPz54MVqZCk
Content-Type: application/json

{
  
}

###

POST http://localhost:5000/v1/api/vaults/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2YXVsdCI6eyJmaXJzdE5hbWUiOiJiIiwibGFzdE5hbWUiOiJiIiwiZW1haWwiOiJiQGIuY29tIiwiaGFzaGVkTWFzdGVyUGFzc3dvcmQiOiIkMmIkMTUkbzJsTDJaLmN0SUt6bkpHQXEzelc1dS5tUjByUmxNYjNVcEcyOEVTVG0xSmdMNFZjek1NekMiLCJfaWQiOiI2NGI3NzRlMGJkM2E5MjA4MTMxOTM2ZWEiLCJfX3YiOjB9LCJpYXQiOjE2ODk3NDQ2MDh9.xz_weuONhzaDwTYIWUg4tezKaXLeTVVVsPz54MVqZCk
Content-Type: application/json

{
  
}

###